version: '2'

services:
  app:
    image: 'sandbox-0.0.1:latest'
    build:
      context: .
    container_name: app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/db1
      - SPRING_DATASOURCE_USERNAME=linux_user
      - SPRING_DATASOURCE_PASSWORD=linux_user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    restart: unless-stopped

